# Generated by Django 3.2.7 on 2021-10-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='product_name',
            new_name='course_name',
        ),
    ]
